Just Js Testings
adamclasic/testing-practice pull request #1
Opened 2020-09-10 08:16 UTC by adamclasic

Added tests for the following functions:

- Capitalized
- ReverseString
- Calculator
- caesarCipher
- arrayAnalysis

2020-09-10 10:01 UTC, suretrust requested changes
Hi @adamclasic, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [ ] Set up linter appropriately.

- [ ] When writing tests for a function, we try to write a test that covers all edge cases so that our function/app will always be completely valid and free of bugs. This also makes refactoring easier.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-09-10 10:01 UTC, suretrust commented on capitalize.test.js
> +});
You could add a test for when `s !== 'string'` as shown in your code.

2020-09-10 10:01 UTC, suretrust commented on reverseString.test.js
> +// const { test } = require('picomatch');
- [ ] Comments: It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  

:x: **commented piece of codes** /\* `.nav { color: red;}` \*/  
:heavy_check_mark: **comments about code** /\* Navigation \*/  
```suggestion
```

2020-09-10 10:01 UTC, suretrust commented on reverseString.test.js
> +  expect(reverseString('hello')).toBe('olleh');
You could add more tests like:
- When the input is not a string.
- When the input contains more than letters, e.g: `'dsh5gje37;]f'`.

2020-09-10 10:01 UTC, suretrust commented on caesar.test.js
> +  expect(caesar('JLKJL;', 5)).toBe('EGFEG6');
* [ ] Add a test for wrapping from `z` to `a`.
* [ ] Add a test for keeping the same case.
* [ ] Add a test for punctuations.

2020-09-10 10:01 UTC, suretrust commented on analyze.test.js
> +});
Let add test for an empty array.

2020-09-10 11:13 UTC, adamclasic commented on reverseString.test.js
> +// const { test } = require('picomatch');
This line is generated by JestJS

2020-09-10 12:09 UTC, adamclasic commented
In some lines where you see Require or commented code, that was generated by Jest.js. Please ignore it.

2020-09-12 18:27 UTC, suretrust approved these changes
Hi @adamclasic, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

2020-09-12 20:37 UTC, merged